// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(config) {
    return config.set({
      basePath: '',
      frameworks: ['jasmine-jquery', 'jasmine'],
      files: [
        'bower_components/angular/angular.js',
        'bower_components/angular-mocks/angular-mocks.js',
        'bower_components/angular-animate/angular-animate.js',
        'src/**/*.module.js',
        'src/**/*.js',
        'test/**/*.js'],
      reporters: ['dots'],
      port: 9876,
      colors: true,
      logLevel: config.LOG_INFO,
      autoWatch: true,
      browsers: ['Chrome'],
      singleRun: false
    });
  };

}).call(this);
